### ISSUE TITLE
Works only JDK18 & above?

### ISSUE THREAD

**Issue by ramkumarkb** [mpe85/grampa#1]
Hi,

Thank you for the fantastic project. The APIs seem very similar to the [Lua's LPEG library](http://lua-users.org/wiki/LpegRecipes) .
While building a small project, I see the following error. Curious to know if this work only with `JDK18` & above?

```
No matching variant of com.github.mpe85:grampa:1.1.0 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability com.github.mpe85:grampa:1.1.0 declares an API of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 18 and the consumer needed a component compatible with Java 11
             - Variant 'runtimeElements' capability com.github.mpe85:grampa:1.1.0 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 18 and the consumer needed a component compatible with Java 11
```

Thank you very much !

**Comment by mpe85** [comment]
@ramkumarkb Sorry for answering so late.
It is designed to work on JDK 8 or higher.
When I have time I'm gonna check whats wrong here.
Can you provide this sample project which shows this error?

**Comment by mpe85** [comment]
@ramkumarkb Sorry for the inconvenience. I had a look at it and and fixed it right away with https://github.com/mpe85/grampa/commit/d3828356b0ed461683802746cdae9767dc0aef59.
The target compatibility was not set correctly. I'll release v1.1.1 soon which will contain the fix.

**Comment by ramkumarkb** [comment]
@mpe85  - Thank you for the response. Yes, for my work I was able to rebuild from the source and then used it as a local library. 

Once again, really high quality parser library (a lot can be learnt from the tests you have written). I will try to contribute an example from the project am working on - to parse a bespoke input txt file from a legacy sytem.

**Comment by mpe85** [comment]
@ramkumarkb Thanks for the feedback!
Maybe you are able now to include Grampa as an external dependency instead of building it locally.
If you have any ideas for new features, please let me know.
